<?php

namespace App\Database\Seeds;

use App\Models\ProductCategoryModel;
use App\Models\ProductModel;
use CodeIgniter\Database\Seeder;

class EcommerceCatalogExpansionSeeder extends Seeder
{
    public function run()
    {
        $categoryModel = new ProductCategoryModel();
        $productModel = new ProductModel();

        $categories = [
            [
                'name' => 'Laptop & Productivity',
                'slug' => 'laptop-productivity',
                'description' => 'Laptop sleeves, stands, docks, and workflow tools for focused work and portable productivity setups.',
                'icon' => 'bi-laptop',
                'display' => 1,
                'sort' => 5,
            ],
            [
                'name' => 'Gaming Peripherals',
                'slug' => 'gaming-peripherals',
                'description' => 'Responsive keyboards, mice, controllers, and accessories built for cleaner inputs and longer sessions.',
                'icon' => 'bi-controller',
                'display' => 1,
                'sort' => 6,
            ],
            [
                'name' => 'Storage & SSD',
                'slug' => 'storage-ssd',
                'description' => 'Internal and external storage picks for faster load times, safer backups, and cleaner file workflows.',
                'icon' => 'bi-device-ssd',
                'display' => 1,
                'sort' => 7,
            ],
            [
                'name' => 'Networking & WiFi',
                'slug' => 'networking-wifi',
                'description' => 'Routers, mesh systems, switches, and adapters that help keep home and office connections stable.',
                'icon' => 'bi-router',
                'display' => 1,
                'sort' => 8,
            ],
            [
                'name' => 'Smart Home Tech',
                'slug' => 'smart-home-tech',
                'description' => 'Connected devices and automation-friendly gear for smarter rooms, cleaner control, and daily convenience.',
                'icon' => 'bi-house-gear',
                'display' => 1,
                'sort' => 9,
            ],
            [
                'name' => 'Power & Charging',
                'slug' => 'power-charging',
                'description' => 'Charging stations, UPS, power strips, and reliable power accessories for work and entertainment setups.',
                'icon' => 'bi-battery-charging',
                'display' => 1,
                'sort' => 10,
            ],
            [
                'name' => 'Streaming & Creator Gear',
                'slug' => 'streaming-creator-gear',
                'description' => 'Microphones, lighting, capture tools, and creator-focused devices for streaming and content production.',
                'icon' => 'bi-camera-video',
                'display' => 1,
                'sort' => 11,
            ],
            [
                'name' => 'Cooling & PC Cases',
                'slug' => 'cooling-pc-cases',
                'description' => 'Airflow cases, fans, coolers, and thermal parts for balanced temperatures and cleaner builds.',
                'icon' => 'bi-fan',
                'display' => 1,
                'sort' => 12,
            ],
            [
                'name' => 'Desk Furniture & Ergonomics',
                'slug' => 'desk-furniture-ergonomics',
                'description' => 'Monitor risers, chairs, desk mats, and ergonomic tools that improve comfort throughout long workdays.',
                'icon' => 'bi-layout-text-sidebar-reverse',
                'display' => 1,
                'sort' => 13,
            ],
            [
                'name' => 'Console & Handheld Gear',
                'slug' => 'console-handheld-gear',
                'description' => 'Cases, docks, charging gear, and gaming add-ons for console setups and portable play.',
                'icon' => 'bi-nintendo-switch',
                'display' => 1,
                'sort' => 14,
            ],
        ];

        $categoryMap = [];
        foreach ($categories as $category) {
            $existingCategory = $categoryModel->getCategoryBySlug($category['slug']);
            $savedCategory = $existingCategory
                ? $categoryModel->updateCategoryById($existingCategory['id'], $category)
                : $categoryModel->insertCategory($category);

            $categoryMap[$category['slug']] = $savedCategory;
        }

        $productsByCategory = [
            'laptop-productivity' => [
                ['sku' => 'LTP-STN-01', 'name' => 'LiftBase Aluminum Laptop Stand', 'slug' => 'liftbase-aluminum-laptop-stand', 'summary' => 'A stable aluminum stand that lifts your screen for cleaner posture and cooler daily laptop use.', 'description' => 'Aluminum laptop stand with an open frame for airflow, cleaner posture, and tidier desk positioning during long work sessions.', 'highlight' => 'Raised viewing angle, strong metal frame, and cleaner cable space for hybrid work desks.', 'price' => 349000, 'stock' => 34, 'is_featured' => 0, 'sort' => 501],
                ['sku' => 'LTP-DCK-02', 'name' => 'DockFlow USB-C Work Hub', 'slug' => 'dockflow-usb-c-work-hub', 'summary' => 'A compact USB-C dock with HDMI, USB-A, and card reader access for modern laptop workflows.', 'description' => 'Productivity dock for creators and office users who need quick access to display output, storage cards, and multiple peripherals.', 'highlight' => 'Single-cable expansion for displays, drives, and daily desk accessories.', 'price' => 799000, 'stock' => 21, 'is_featured' => 1, 'sort' => 502],
                ['sku' => 'LTP-SLV-03', 'name' => 'TransitShield 14 Laptop Sleeve', 'slug' => 'transitshield-14-laptop-sleeve', 'summary' => 'A padded sleeve designed to protect your laptop during commutes, meetings, and everyday travel.', 'description' => 'Soft-lined laptop sleeve with structured padding and accessory space for chargers, cables, and workday essentials.', 'highlight' => 'Slim carry profile with practical protection for daily mobility.', 'price' => 259000, 'stock' => 40, 'is_featured' => 0, 'sort' => 503],
                ['sku' => 'LTP-MSE-04', 'name' => 'ClickEase Silent Travel Mouse', 'slug' => 'clickease-silent-travel-mouse', 'summary' => 'A quiet wireless mouse built for portable productivity, shared spaces, and lightweight carry.', 'description' => 'Compact mouse with low-noise clicks and dependable wireless performance for students, remote workers, and mobile setups.', 'highlight' => 'Quiet clicks and compact shape for cafés, meetings, and shared desks.', 'price' => 289000, 'stock' => 37, 'is_featured' => 0, 'sort' => 504],
                ['sku' => 'LTP-KPD-05', 'name' => 'NumPad Air Bluetooth Keypad', 'slug' => 'numpad-air-bluetooth-keypad', 'summary' => 'A slim numeric keypad for spreadsheet-heavy work and cleaner accounting workflows on compact laptops.', 'description' => 'Wireless numeric keypad designed for finance, bookkeeping, and operations users who want faster number entry.', 'highlight' => 'Quick number input without giving up a compact laptop setup.', 'price' => 319000, 'stock' => 18, 'is_featured' => 0, 'sort' => 505],
                ['sku' => 'LTP-BGS-06', 'name' => 'MetroPack Tech Messenger', 'slug' => 'metropack-tech-messenger', 'summary' => 'A work-ready bag with compartments for laptops, chargers, documents, and everyday commuter gear.', 'description' => 'Tech messenger bag made for neat device carry with practical dividers for accessories and daily office movement.', 'highlight' => 'Organized carry space for laptop, charger, notebook, and tech accessories.', 'price' => 649000, 'stock' => 16, 'is_featured' => 0, 'sort' => 506],
                ['sku' => 'LTP-WEB-07', 'name' => 'ClearFrame 2K Webcam', 'slug' => 'clearframe-2k-webcam', 'summary' => 'A sharp webcam for meetings, remote interviews, and everyday hybrid work communication.', 'description' => 'Plug-and-play webcam with clear image output and desk-friendly mounting for calls, teaching, and collaborative work.', 'highlight' => 'Sharper meetings with cleaner framing and easy setup.', 'price' => 899000, 'stock' => 12, 'is_featured' => 1, 'sort' => 507],
                ['sku' => 'LTP-ARM-08', 'name' => 'ViewLift Portable Monitor Arm', 'slug' => 'viewlift-portable-monitor-arm', 'summary' => 'A lightweight support arm that helps build a flexible dual-screen productivity corner.', 'description' => 'Portable desk arm designed for temporary setups, co-working spaces, or hybrid desks that need quick monitor repositioning.', 'highlight' => 'Better viewing angles and cleaner workspace movement.', 'price' => 559000, 'stock' => 9, 'is_featured' => 0, 'sort' => 508],
                ['sku' => 'LTP-CBL-09', 'name' => 'WorkLine Cable Organizer Kit', 'slug' => 'workline-cable-organizer-kit', 'summary' => 'A tidy cable kit that helps keep chargers, adapters, and desk accessories under control.', 'description' => 'Desk cable organizer pack for keeping workstations cleaner, safer, and easier to manage every day.', 'highlight' => 'Simple cable control for cleaner desks and fewer tangles.', 'price' => 129000, 'stock' => 55, 'is_featured' => 0, 'sort' => 509],
                ['sku' => 'LTP-PWR-10', 'name' => 'TravelVolt 65W Laptop Charger', 'slug' => 'travelvolt-65w-laptop-charger', 'summary' => 'A compact USB-C charger for lightweight laptop travel, mobile work, and all-day power top-ups.', 'description' => 'Portable 65W charger that helps simplify daily carry for laptops, tablets, and USB-C phones.', 'highlight' => 'Smaller carry footprint with dependable USB-C laptop charging.', 'price' => 469000, 'stock' => 28, 'is_featured' => 0, 'sort' => 510],
            ],
            'gaming-peripherals' => [
                ['sku' => 'GMP-MSE-01', 'name' => 'SwiftAim RGB Gaming Mouse', 'slug' => 'swiftaim-rgb-gaming-mouse', 'summary' => 'A responsive gaming mouse with fast tracking and a shape that stays comfortable through long sessions.', 'description' => 'Gaming mouse designed for stable tracking, controlled grip, and smoother daily play across competitive and casual titles.', 'highlight' => 'Responsive tracking with a shape tuned for longer sessions.', 'price' => 459000, 'stock' => 31, 'is_featured' => 1, 'sort' => 601],
                ['sku' => 'GMP-KBD-02', 'name' => 'StrikeCore TKL Keyboard', 'slug' => 'strikecore-tkl-keyboard', 'summary' => 'A tenkeyless mechanical keyboard built for cleaner desk space and sharper gaming inputs.', 'description' => 'Compact gaming keyboard with responsive switches, solid construction, and a layout that leaves more mouse room.', 'highlight' => 'Compact format with fast key response and cleaner desk positioning.', 'price' => 999000, 'stock' => 17, 'is_featured' => 1, 'sort' => 602],
                ['sku' => 'GMP-MAT-03', 'name' => 'GlideZone Extended Mousepad', 'slug' => 'glidezone-extended-mousepad', 'summary' => 'A wide mousepad that gives keyboards and mice a consistent surface for stable everyday play.', 'description' => 'Extended desk mat with smooth glide and stitched edges for gaming setups that need a cleaner landing area.', 'highlight' => 'Wide coverage and consistent glide for desk-wide setups.', 'price' => 229000, 'stock' => 44, 'is_featured' => 0, 'sort' => 603],
                ['sku' => 'GMP-HST-04', 'name' => 'EchoLite Gaming Headset Stand', 'slug' => 'echolite-gaming-headset-stand', 'summary' => 'A minimal stand that keeps your headset protected, visible, and easier to reach between sessions.', 'description' => 'Headset stand that helps declutter desks while keeping gaming audio gear ready to grab.', 'highlight' => 'Simple display and protection for daily-use headsets.', 'price' => 179000, 'stock' => 26, 'is_featured' => 0, 'sort' => 604],
                ['sku' => 'GMP-PAD-05', 'name' => 'PulseGrip Controller Grip Set', 'slug' => 'pulsegrip-controller-grip-set', 'summary' => 'A grip accessory set for players who want more control and comfort during longer controller sessions.', 'description' => 'Controller grip kit designed to improve handling and reduce hand fatigue during action-heavy play.', 'highlight' => 'More confident hold for longer console sessions.', 'price' => 149000, 'stock' => 30, 'is_featured' => 0, 'sort' => 605],
                ['sku' => 'GMP-MIC-06', 'name' => 'TeamTalk USB Gaming Mic', 'slug' => 'teamtalk-usb-gaming-mic', 'summary' => 'A desk microphone for clearer squad chat, streaming starts, and cleaner voice pickup.', 'description' => 'USB desktop microphone built for gamers who want clearer communication without a complicated setup.', 'highlight' => 'Cleaner voice clarity for chat, co-op play, and first-time streaming.', 'price' => 699000, 'stock' => 13, 'is_featured' => 0, 'sort' => 606],
                ['sku' => 'GMP-LGT-07', 'name' => 'ArenaGlow RGB Light Bars', 'slug' => 'arenaglow-rgb-light-bars', 'summary' => 'Desk lighting bars that add atmosphere to gaming corners without taking over the whole setup.', 'description' => 'RGB lighting pair for gamers who want more mood around monitors, shelves, or compact entertainment desks.', 'highlight' => 'Ambient setup lighting that upgrades the desk mood fast.', 'price' => 389000, 'stock' => 19, 'is_featured' => 0, 'sort' => 607],
                ['sku' => 'GMP-CAM-08', 'name' => 'FaceFocus Stream Cam', 'slug' => 'facefocus-stream-cam', 'summary' => 'A creator-friendly camera for streamers who need a sharper face cam without a complex setup.', 'description' => 'Web camera that helps entry-level streamers and gaming creators look clearer on calls and streams.', 'highlight' => 'Easy streaming upgrade for cleaner on-camera presence.', 'price' => 849000, 'stock' => 11, 'is_featured' => 0, 'sort' => 608],
                ['sku' => 'GMP-DCK-09', 'name' => 'TurboCharge Controller Dock', 'slug' => 'turbocharge-controller-dock', 'summary' => 'A charging dock that keeps controllers powered and neatly parked between gaming sessions.', 'description' => 'Controller charging dock made for desk or console corners where neat charging matters.', 'highlight' => 'Convenient charging and cleaner storage for controller users.', 'price' => 329000, 'stock' => 22, 'is_featured' => 0, 'sort' => 609],
                ['sku' => 'GMP-SPK-10', 'name' => 'BoomBeat Desktop Speakers', 'slug' => 'boombeat-desktop-speakers', 'summary' => 'A speaker pair that adds more impact to everyday gaming, music, and casual media playback.', 'description' => 'Compact desktop speakers for users who want stronger sound than monitor audio without bulky gear.', 'highlight' => 'Desk-friendly audio with more presence for games and music.', 'price' => 579000, 'stock' => 14, 'is_featured' => 0, 'sort' => 610],
            ],
            'storage-ssd' => [
                ['sku' => 'SSD-NVME-01', 'name' => 'FlashCore 1TB NVMe SSD', 'slug' => 'flashcore-1tb-nvme-ssd', 'summary' => 'A fast NVMe SSD for quicker boot times, lighter game loads, and smoother daily file access.', 'description' => 'PCIe NVMe storage built for users upgrading from slower drives and looking for cleaner everyday responsiveness.', 'highlight' => 'Faster boots, quicker file access, and an easy system upgrade path.', 'price' => 999000, 'stock' => 24, 'is_featured' => 1, 'sort' => 701],
                ['sku' => 'SSD-SATA-02', 'name' => 'StableStore 2TB SATA SSD', 'slug' => 'stablestore-2tb-sata-ssd', 'summary' => 'A dependable SATA SSD for users who need more storage space without complicating older desktop builds.', 'description' => 'High-capacity solid-state storage suitable for older systems, secondary drives, and budget-conscious upgrades.', 'highlight' => 'Large capacity and dependable performance for secondary storage upgrades.', 'price' => 1399000, 'stock' => 18, 'is_featured' => 0, 'sort' => 702],
                ['sku' => 'SSD-EXT-03', 'name' => 'VaultGo 1TB Portable SSD', 'slug' => 'vaultgo-1tb-portable-ssd', 'summary' => 'A compact external SSD for moving project files, media, and backups between devices quickly.', 'description' => 'Pocketable external solid-state storage for creators, students, and mobile professionals who need faster file carry.', 'highlight' => 'Fast portable storage for work files, media, and backups.', 'price' => 1249000, 'stock' => 20, 'is_featured' => 1, 'sort' => 703],
                ['sku' => 'SSD-HDD-04', 'name' => 'ArchiveMax 4TB Backup Drive', 'slug' => 'archivemax-4tb-backup-drive', 'summary' => 'A roomy backup drive built for archive storage, media libraries, and practical long-term file keeping.', 'description' => 'Desktop storage drive aimed at users who want dedicated local backup space for projects and personal archives.', 'highlight' => 'High-capacity file backup without overcomplicating your setup.', 'price' => 1699000, 'stock' => 15, 'is_featured' => 0, 'sort' => 704],
                ['sku' => 'SSD-ENC-05', 'name' => 'DriveShell SSD Enclosure', 'slug' => 'driveshell-ssd-enclosure', 'summary' => 'A tool-free enclosure that turns spare SSDs into portable storage for quick file movement.', 'description' => 'External enclosure for reusing internal SSDs as portable drives without a complicated install process.', 'highlight' => 'Quick SSD reuse for portable storage and easy drive access.', 'price' => 239000, 'stock' => 33, 'is_featured' => 0, 'sort' => 705],
                ['sku' => 'SSD-HUB-06', 'name' => 'MediaDock Card and SSD Hub', 'slug' => 'mediadock-card-and-ssd-hub', 'summary' => 'A transfer hub designed for photographers, editors, and users who move large files every day.', 'description' => 'Transfer-focused hub with card reader and storage access for cleaner project handoffs and mobile workflows.', 'highlight' => 'Faster media transfer for creators and file-heavy workflows.', 'price' => 659000, 'stock' => 12, 'is_featured' => 0, 'sort' => 706],
                ['sku' => 'SSD-CLN-07', 'name' => 'ThermoPad SSD Cooling Kit', 'slug' => 'thermopad-ssd-cooling-kit', 'summary' => 'A cooling kit that helps maintain stable SSD performance inside tighter desktop or notebook spaces.', 'description' => 'Thermal pads and heat spreaders for users who want cooler storage performance in compact builds.', 'highlight' => 'Simple thermal upgrade for cleaner storage temperatures.', 'price' => 119000, 'stock' => 46, 'is_featured' => 0, 'sort' => 707],
                ['sku' => 'SSD-NAS-08', 'name' => 'HomeKeep NAS Drive 6TB', 'slug' => 'homekeep-nas-drive-6tb', 'summary' => 'A NAS-ready hard drive for family backup, home servers, and central media storage.', 'description' => 'Network storage drive built for reliable always-on use in small office or home data setups.', 'highlight' => 'A practical pick for shared storage and home backup systems.', 'price' => 2199000, 'stock' => 8, 'is_featured' => 0, 'sort' => 708],
                ['sku' => 'SSD-CAB-09', 'name' => 'SpeedLink SATA Cable Pack', 'slug' => 'speedlink-sata-cable-pack', 'summary' => 'A practical cable bundle for storage upgrades, clean builds, and replacement desktop connections.', 'description' => 'SATA cable set for builders and upgraders who want spare cables ready during installs or maintenance.', 'highlight' => 'Useful spare cables for storage installs and cleanup work.', 'price' => 79000, 'stock' => 52, 'is_featured' => 0, 'sort' => 709],
                ['sku' => 'SSD-MNT-10', 'name' => 'FlexTray 2.5 Drive Mount Kit', 'slug' => 'flextray-25-drive-mount-kit', 'summary' => 'A mounting kit for cleaner SSD placement inside desktops that need better storage organization.', 'description' => 'Drive mounting set built for easier SSD placement in cases that need extra brackets or cleaner storage alignment.', 'highlight' => 'Small accessory that makes storage upgrades easier to finish neatly.', 'price' => 99000, 'stock' => 38, 'is_featured' => 0, 'sort' => 710],
            ],
            'networking-wifi' => [
                ['sku' => 'NET-ROU-01', 'name' => 'WaveMesh AX3000 Router', 'slug' => 'wavemesh-ax3000-router', 'summary' => 'A modern WiFi router for households that need smoother streaming, gaming, and work calls.', 'description' => 'WiFi router designed for stable household coverage, better device handling, and modern daily internet use.', 'highlight' => 'Stronger everyday home WiFi for streaming, gaming, and work.', 'price' => 1499000, 'stock' => 13, 'is_featured' => 1, 'sort' => 801],
                ['sku' => 'NET-MSH-02', 'name' => 'LinkNest Dual Pack Mesh WiFi', 'slug' => 'linknest-dual-pack-mesh-wifi', 'summary' => 'A mesh WiFi system for wider home coverage and fewer dead zones across rooms and floors.', 'description' => 'Two-node mesh system built for families who want simpler setup and better signal reach in larger spaces.', 'highlight' => 'Cleaner coverage across larger homes and shared spaces.', 'price' => 2399000, 'stock' => 9, 'is_featured' => 1, 'sort' => 802],
                ['sku' => 'NET-SWT-03', 'name' => 'PortPlus 8-Port Gigabit Switch', 'slug' => 'portplus-8-port-gigabit-switch', 'summary' => 'A compact network switch for adding more wired ports to desktop, NAS, and entertainment setups.', 'description' => 'Gigabit network switch built for stable wired expansion at home or in small offices.', 'highlight' => 'More wired ports for cleaner and more stable connections.', 'price' => 399000, 'stock' => 27, 'is_featured' => 0, 'sort' => 803],
                ['sku' => 'NET-USB-04', 'name' => 'AirPlug WiFi 6 USB Adapter', 'slug' => 'airplug-wifi-6-usb-adapter', 'summary' => 'A USB adapter that upgrades older desktops or laptops to stronger, faster wireless connectivity.', 'description' => 'WiFi adapter for users who want a simple wireless upgrade without changing their entire system.', 'highlight' => 'Quick wireless upgrade for older PCs and notebooks.', 'price' => 329000, 'stock' => 25, 'is_featured' => 0, 'sort' => 804],
                ['sku' => 'NET-CBL-05', 'name' => 'PureLink Cat6 Cable Set', 'slug' => 'purelink-cat6-cable-set', 'summary' => 'A durable Ethernet cable pack for faster wired setups and cleaner desk-to-router connections.', 'description' => 'Cat6 cable set suited for desks, routers, smart TVs, and office endpoints that benefit from stable wired speed.', 'highlight' => 'Reliable wired networking with cleaner desk routing.', 'price' => 149000, 'stock' => 48, 'is_featured' => 0, 'sort' => 805],
                ['sku' => 'NET-UPS-06', 'name' => 'StayOnline Mini UPS', 'slug' => 'stayonline-mini-ups', 'summary' => 'A compact backup power unit that helps keep routers alive during short outages or unstable power.', 'description' => 'Mini UPS made for modem and router continuity when power flickers interrupt work or home connectivity.', 'highlight' => 'Keeps core internet gear online during short power drops.', 'price' => 589000, 'stock' => 14, 'is_featured' => 0, 'sort' => 806],
                ['sku' => 'NET-CAM-07', 'name' => 'WatchGrid Indoor Security Cam', 'slug' => 'watchgrid-indoor-security-cam', 'summary' => 'A smart camera for indoor monitoring, room checks, and connected home awareness.', 'description' => 'Indoor security camera with app connectivity for daily room monitoring and family awareness.', 'highlight' => 'Simple indoor monitoring for connected households.', 'price' => 499000, 'stock' => 19, 'is_featured' => 0, 'sort' => 807],
                ['sku' => 'NET-RPT-08', 'name' => 'SignalBoost WiFi Repeater', 'slug' => 'signalboost-wifi-repeater', 'summary' => 'A compact repeater that helps extend wireless reach into low-signal corners of the home.', 'description' => 'Wireless repeater designed for everyday households looking to improve weak room coverage quickly.', 'highlight' => 'Practical fix for weak-signal rooms and corners.', 'price' => 279000, 'stock' => 23, 'is_featured' => 0, 'sort' => 808],
                ['sku' => 'NET-BRD-09', 'name' => 'NetBoard Cable Organizer Rack', 'slug' => 'netboard-cable-organizer-rack', 'summary' => 'A neat cable organizer rack for modem, switch, and router areas that tend to get messy fast.', 'description' => 'Organizer shelf for reducing clutter around networking equipment and improving access to ports and adapters.', 'highlight' => 'Cleaner router corners and easier cable organization.', 'price' => 189000, 'stock' => 20, 'is_featured' => 0, 'sort' => 809],
                ['sku' => 'NET-PWR-10', 'name' => 'RouterSafe Surge Protector', 'slug' => 'routersafe-surge-protector', 'summary' => 'A surge protector designed to help shield networking gear and home office hardware from unstable power.', 'description' => 'Power strip with surge safety features for networking setups, desks, and compact work corners.', 'highlight' => 'Smarter protection for routers, adapters, and desk electronics.', 'price' => 219000, 'stock' => 29, 'is_featured' => 0, 'sort' => 810],
            ],
            'smart-home-tech' => [
                ['sku' => 'SMT-LMP-01', 'name' => 'AuraGlow Smart Desk Lamp', 'slug' => 'auraglow-smart-desk-lamp', 'summary' => 'A smart desk lamp with adjustable tones for focused work, late study sessions, and evening reading.', 'description' => 'Connected desk lamp that makes it easier to shift lighting mood across work, reading, and casual home moments.', 'highlight' => 'Flexible lighting that adapts to work mode and evening comfort.', 'price' => 549000, 'stock' => 18, 'is_featured' => 1, 'sort' => 901],
                ['sku' => 'SMT-PLG-02', 'name' => 'SyncPlug Smart Outlet Duo', 'slug' => 'syncplug-smart-outlet-duo', 'summary' => 'A smart plug pair for scheduling lights, charging stations, and simple home automation tasks.', 'description' => 'Connected outlet set for convenient timer-based control over small electronics and room appliances.', 'highlight' => 'Easy automation for lamps, chargers, and desk power routines.', 'price' => 299000, 'stock' => 34, 'is_featured' => 0, 'sort' => 902],
                ['sku' => 'SMT-SPK-03', 'name' => 'RoomVoice Mini Smart Speaker', 'slug' => 'roomvoice-mini-smart-speaker', 'summary' => 'A compact smart speaker for voice commands, timers, and simple connected-home control.', 'description' => 'Voice-enabled speaker built for households that want music, reminders, and connected-home control in one spot.', 'highlight' => 'Voice convenience for daily routines and room control.', 'price' => 799000, 'stock' => 16, 'is_featured' => 1, 'sort' => 903],
                ['sku' => 'SMT-LCK-04', 'name' => 'EntryGuard Smart Door Lock', 'slug' => 'entryguard-smart-door-lock', 'summary' => 'A connected lock designed for easier home access control, guest entry, and everyday convenience.', 'description' => 'Smart door lock built to simplify access management in homes, rentals, and modern living spaces.', 'highlight' => 'Smarter access control without carrying extra keys everywhere.', 'price' => 2499000, 'stock' => 6, 'is_featured' => 0, 'sort' => 904],
                ['sku' => 'SMT-CAM-05', 'name' => 'HomeWatch 360 Camera', 'slug' => 'homewatch-360-camera', 'summary' => 'A rotating indoor smart camera for wider room coverage and more flexible home monitoring.', 'description' => 'Indoor connected camera with wider movement coverage for pet checks, hallway monitoring, and daily home awareness.', 'highlight' => 'Wider room visibility with easy app-based monitoring.', 'price' => 689000, 'stock' => 15, 'is_featured' => 0, 'sort' => 905],
                ['sku' => 'SMT-SNS-06', 'name' => 'SafeSense Door Sensor Kit', 'slug' => 'safesense-door-sensor-kit', 'summary' => 'A door and window sensor kit for entry notifications and smarter room awareness.', 'description' => 'Simple sensor pack for connected home notifications on doors, cabinets, and room entry points.', 'highlight' => 'Straightforward room entry alerts and automation triggers.', 'price' => 359000, 'stock' => 22, 'is_featured' => 0, 'sort' => 906],
                ['sku' => 'SMT-VAC-07', 'name' => 'SweepMate Smart Robot Vacuum', 'slug' => 'sweepmate-smart-robot-vacuum', 'summary' => 'A robot vacuum that helps keep home offices and common areas cleaner with less manual effort.', 'description' => 'Smart cleaning device designed for daily floor upkeep in home workspaces, bedrooms, and shared rooms.', 'highlight' => 'Automated cleaning for tidier everyday living spaces.', 'price' => 2799000, 'stock' => 7, 'is_featured' => 1, 'sort' => 907],
                ['sku' => 'SMT-LED-08', 'name' => 'ColorLoop Smart Light Strip', 'slug' => 'colorloop-smart-light-strip', 'summary' => 'A flexible smart light strip for shelves, desks, TV areas, and mood-driven room setups.', 'description' => 'Connected ambient lighting strip that adds room character around desks, gaming corners, and entertainment setups.', 'highlight' => 'Fast room atmosphere upgrade with flexible placement.', 'price' => 269000, 'stock' => 27, 'is_featured' => 0, 'sort' => 908],
                ['sku' => 'SMT-HUB-09', 'name' => 'HomeNode Automation Hub', 'slug' => 'homenode-automation-hub', 'summary' => 'A central smart hub that helps keep connected devices simpler to manage from one place.', 'description' => 'Smart home hub for users who want cleaner device coordination across sensors, plugs, and lighting routines.', 'highlight' => 'Centralized control for connected rooms and routines.', 'price' => 999000, 'stock' => 10, 'is_featured' => 0, 'sort' => 909],
                ['sku' => 'SMT-AIR-10', 'name' => 'PureDesk Smart Air Monitor', 'slug' => 'puredesk-smart-air-monitor', 'summary' => 'A compact air monitor for tracking indoor conditions in bedrooms, home offices, and living spaces.', 'description' => 'Room air monitor built for users who want clearer insight into temperature, humidity, and air quality trends.', 'highlight' => 'Simple air insights for more comfortable rooms.', 'price' => 619000, 'stock' => 12, 'is_featured' => 0, 'sort' => 910],
            ],
            'power-charging' => [
                ['sku' => 'PWR-CHG-01', 'name' => 'ChargeDeck 6-Port Station', 'slug' => 'chargedeck-6-port-station', 'summary' => 'A multi-device charging station for phones, tablets, earbuds, and daily desk accessories.', 'description' => 'Charging hub created for households and desks that need a neater place to power multiple personal devices.', 'highlight' => 'Neater daily charging for multiple devices in one place.', 'price' => 599000, 'stock' => 25, 'is_featured' => 1, 'sort' => 1001],
                ['sku' => 'PWR-BNK-02', 'name' => 'PowerSprint 20K Power Bank', 'slug' => 'powersprint-20k-power-bank', 'summary' => 'A high-capacity power bank for commuters, travelers, and people who need backup power on long days.', 'description' => 'Portable battery solution built to keep phones, handhelds, and smaller USB-C gear powered through busy schedules.', 'highlight' => 'Reliable backup power for travel, commute, and daily carry.', 'price' => 699000, 'stock' => 28, 'is_featured' => 1, 'sort' => 1002],
                ['sku' => 'PWR-GAN-03', 'name' => 'MiniVolt 45W GaN Charger', 'slug' => 'minivolt-45w-gan-charger', 'summary' => 'A compact fast charger that fits lighter daily carry without sacrificing charging speed.', 'description' => 'Small-form GaN charger for phones, tablets, and light laptops where portability matters most.', 'highlight' => 'Compact fast charging for lighter travel bags and daily commutes.', 'price' => 329000, 'stock' => 36, 'is_featured' => 0, 'sort' => 1003],
                ['sku' => 'PWR-UPS-04', 'name' => 'SteadyLine 1200VA UPS', 'slug' => 'steadyline-1200va-ups', 'summary' => 'A desktop UPS for keeping routers, workstations, and small electronics safer during unstable power.', 'description' => 'Backup power unit for desks and home offices that need short-run protection during outages and voltage drops.', 'highlight' => 'More confidence for routers, PCs, and work-from-home essentials.', 'price' => 1699000, 'stock' => 11, 'is_featured' => 0, 'sort' => 1004],
                ['sku' => 'PWR-STR-05', 'name' => 'SafeDock Surge Power Strip', 'slug' => 'safedock-surge-power-strip', 'summary' => 'A surge-protected power strip for tidier desks and safer charging around daily electronics.', 'description' => 'Multi-outlet power strip aimed at desks, entertainment corners, and productivity areas with multiple electronics.', 'highlight' => 'More outlets and better protection for busy desk setups.', 'price' => 249000, 'stock' => 42, 'is_featured' => 0, 'sort' => 1005],
                ['sku' => 'PWR-MAG-06', 'name' => 'SnapCharge Mag Dock', 'slug' => 'snapcharge-mag-dock', 'summary' => 'A magnetic charging dock built for simpler nightstand and workdesk phone charging.', 'description' => 'Magnetic charging dock for users who want easier phone placement and cleaner everyday charging habits.', 'highlight' => 'Simpler magnetic charging with a cleaner desk footprint.', 'price' => 419000, 'stock' => 20, 'is_featured' => 0, 'sort' => 1006],
                ['sku' => 'PWR-CAR-07', 'name' => 'RoadVolt Dual Car Charger', 'slug' => 'roadvolt-dual-car-charger', 'summary' => 'A compact in-car charger for keeping phones and passenger devices powered on the move.', 'description' => 'Vehicle charger designed for commuters, ride-share drivers, and road trips where fast charging matters.', 'highlight' => 'Reliable dual-device charging during commutes and road travel.', 'price' => 159000, 'stock' => 31, 'is_featured' => 0, 'sort' => 1007],
                ['sku' => 'PWR-CBL-08', 'name' => 'FlexCharge Braided Cable Set', 'slug' => 'flexcharge-braided-cable-set', 'summary' => 'A cable bundle built for desks, nightstands, travel pouches, and everyday backup charging needs.', 'description' => 'Braided cable set created for users who need durable daily charging across phones, tablets, and accessories.', 'highlight' => 'Practical cable bundle for daily charging and backup use.', 'price' => 139000, 'stock' => 58, 'is_featured' => 0, 'sort' => 1008],
                ['sku' => 'PWR-WLS-09', 'name' => 'HaloPad Wireless Charger', 'slug' => 'halopad-wireless-charger', 'summary' => 'A simple wireless pad that keeps phones charged without extra cable clutter on the desk.', 'description' => 'Wireless charging pad for casual daily power top-ups in bedrooms, desks, and common areas.', 'highlight' => 'Cleaner charging with fewer visible desk cables.', 'price' => 279000, 'stock' => 29, 'is_featured' => 0, 'sort' => 1009],
                ['sku' => 'PWR-BAT-10', 'name' => 'ReserveCell AA and AAA Kit', 'slug' => 'reservecell-aa-and-aaa-kit', 'summary' => 'A rechargeable battery kit for devices that still depend on AA and AAA power around the home.', 'description' => 'Rechargeable battery set for remotes, controllers, portable accessories, and household gadgets.', 'highlight' => 'Useful backup power for everyday devices and accessories.', 'price' => 219000, 'stock' => 39, 'is_featured' => 0, 'sort' => 1010],
            ],
            'streaming-creator-gear' => [
                ['sku' => 'CR8-MIC-01', 'name' => 'VoiceCast USB Condenser Mic', 'slug' => 'voicecast-usb-condenser-mic', 'summary' => 'A USB microphone for podcasts, streaming, meetings, and clearer voice capture on a compact desk.', 'description' => 'Creator-friendly microphone made for streamers, podcasters, and professionals who want clearer audio fast.', 'highlight' => 'Cleaner voice capture for streaming, calls, and recorded content.', 'price' => 1099000, 'stock' => 14, 'is_featured' => 1, 'sort' => 1101],
                ['sku' => 'CR8-LGT-02', 'name' => 'StudioGlow Ring Light', 'slug' => 'studioglow-ring-light', 'summary' => 'A desk-friendly ring light that helps faces look more even and camera-ready for streaming or meetings.', 'description' => 'Lighting tool for creators and remote workers who want cleaner face lighting without a complicated setup.', 'highlight' => 'More flattering lighting for calls, content, and camera work.', 'price' => 459000, 'stock' => 18, 'is_featured' => 1, 'sort' => 1102],
                ['sku' => 'CR8-CAP-03', 'name' => 'GameLink HDMI Capture Box', 'slug' => 'gamelink-hdmi-capture-box', 'summary' => 'A capture device for recording or streaming console play with a cleaner desktop workflow.', 'description' => 'Capture hardware built for creators who want an easier path into streaming and gameplay recording.', 'highlight' => 'Simple console capture for entry-level streaming setups.', 'price' => 1399000, 'stock' => 8, 'is_featured' => 0, 'sort' => 1103],
                ['sku' => 'CR8-ARM-04', 'name' => 'CreatorFlex Boom Arm', 'slug' => 'creatorflex-boom-arm', 'summary' => 'A boom arm for positioning microphones more cleanly in streaming and recording setups.', 'description' => 'Adjustable mic arm that helps keep desks cleaner while improving speaking position and workspace flexibility.', 'highlight' => 'Better mic placement with less desk clutter.', 'price' => 329000, 'stock' => 27, 'is_featured' => 0, 'sort' => 1104],
                ['sku' => 'CR8-CAM-05', 'name' => 'FrameFocus Creator Camera', 'slug' => 'framefocus-creator-camera', 'summary' => 'A creator camera built for sharper live sessions, social clips, and polished work calls.', 'description' => 'Desk camera designed for creators who want clearer framing, cleaner image quality, and easy setup.', 'highlight' => 'Sharper on-camera quality for creators and presenters.', 'price' => 1499000, 'stock' => 10, 'is_featured' => 1, 'sort' => 1105],
                ['sku' => 'CR8-BRD-06', 'name' => 'ScenePad Stream Deck Mini', 'slug' => 'scenepad-stream-deck-mini', 'summary' => 'A compact shortcut pad that speeds up scene changes, hotkeys, and stream control actions.', 'description' => 'Shortcut control pad for streamers and content creators who want smoother live switching and production control.', 'highlight' => 'Faster scene control and production shortcuts in one compact pad.', 'price' => 1299000, 'stock' => 9, 'is_featured' => 0, 'sort' => 1106],
                ['sku' => 'CR8-GRN-07', 'name' => 'BackdropGo Foldable Green Screen', 'slug' => 'backdropgo-foldable-green-screen', 'summary' => 'A foldable green screen for tidier video calls, live backgrounds, and compact content spaces.', 'description' => 'Portable background tool for small rooms and creators who need a cleaner visual setup behind the camera.', 'highlight' => 'Cleaner streaming or video backgrounds without a permanent studio setup.', 'price' => 899000, 'stock' => 12, 'is_featured' => 0, 'sort' => 1107],
                ['sku' => 'CR8-SPK-08', 'name' => 'MixCue Monitor Headphones', 'slug' => 'mixcue-monitor-headphones', 'summary' => 'A pair of monitoring headphones for editing, streaming checks, and focused desk listening.', 'description' => 'Closed-back monitoring headphones for creators who want clearer playback while editing or preparing content.', 'highlight' => 'Focused monitoring for editing, streaming, and recording checks.', 'price' => 759000, 'stock' => 15, 'is_featured' => 0, 'sort' => 1108],
                ['sku' => 'CR8-SSD-09', 'name' => 'CreatorVault 2TB Portable SSD', 'slug' => 'creatorvault-2tb-portable-ssd', 'summary' => 'A fast portable SSD for moving footage, project files, and creative assets between machines.', 'description' => 'External storage built for creators who handle large files, quick backups, and mobile editing workflows.', 'highlight' => 'Portable speed for footage transfer, backups, and project carry.', 'price' => 1999000, 'stock' => 11, 'is_featured' => 0, 'sort' => 1109],
                ['sku' => 'CR8-LMP-10', 'name' => 'ColorTone Key Light Pair', 'slug' => 'colortone-key-light-pair', 'summary' => 'A key light pair that helps creators shape brighter, more balanced lighting for streams and studio desks.', 'description' => 'Lighting kit for streamers, product shooters, and on-camera creators who want more control over scene brightness.', 'highlight' => 'Better-balanced desk or studio lighting for creator workflows.', 'price' => 1799000, 'stock' => 7, 'is_featured' => 0, 'sort' => 1110],
            ],
            'cooling-pc-cases' => [
                ['sku' => 'CLG-CASE-01', 'name' => 'AirFrame Mid Tower Case', 'slug' => 'airframe-mid-tower-case', 'summary' => 'A mid-tower case designed for cleaner airflow, neater cable routing, and approachable build flexibility.', 'description' => 'PC case for builders who want balanced airflow, component space, and a clean presentation without excess bulk.', 'highlight' => 'Balanced airflow and cleaner cable routing for modern builds.', 'price' => 1199000, 'stock' => 12, 'is_featured' => 1, 'sort' => 1201],
                ['sku' => 'CLG-FAN-02', 'name' => 'FrostSpin RGB Fan Trio', 'slug' => 'frostspin-rgb-fan-trio', 'summary' => 'A three-pack of case fans for stronger airflow and a more polished internal build look.', 'description' => 'Case fan set built for airflow improvement and cleaner visual consistency in gaming or workstation desktops.', 'highlight' => 'More airflow with coordinated lighting and a cleaner build look.', 'price' => 499000, 'stock' => 24, 'is_featured' => 1, 'sort' => 1202],
                ['sku' => 'CLG-AIO-03', 'name' => 'CoolFlow 240 Liquid Cooler', 'slug' => 'coolflow-240-liquid-cooler', 'summary' => 'A 240mm liquid cooler for users who want stronger thermal control under heavier gaming or work loads.', 'description' => 'Liquid CPU cooling solution aimed at builders who want quieter operation and improved thermal headroom.', 'highlight' => 'Stronger cooling for sustained workloads and cleaner thermals.', 'price' => 1499000, 'stock' => 10, 'is_featured' => 0, 'sort' => 1203],
                ['sku' => 'CLG-CPU-04', 'name' => 'BreezeCore Tower Air Cooler', 'slug' => 'breezecore-tower-air-cooler', 'summary' => 'A tower air cooler that balances performance, reliability, and easier everyday installation.', 'description' => 'Air cooler for builders who prefer lower maintenance and dependable CPU cooling without liquid components.', 'highlight' => 'Dependable tower cooling with a simpler install path.', 'price' => 559000, 'stock' => 19, 'is_featured' => 0, 'sort' => 1204],
                ['sku' => 'CLG-PST-05', 'name' => 'ThermaPro Thermal Paste', 'slug' => 'thermapro-thermal-paste', 'summary' => 'A thermal paste option for cleaner CPU installations, cooler contact, and routine maintenance work.', 'description' => 'Thermal paste suited for fresh builds, cooler swaps, and general maintenance across desktop systems.', 'highlight' => 'A small but useful upgrade for steadier thermal transfer.', 'price' => 109000, 'stock' => 61, 'is_featured' => 0, 'sort' => 1205],
                ['sku' => 'CLG-BKT-06', 'name' => 'BracketFlex GPU Support Stand', 'slug' => 'bracketflex-gpu-support-stand', 'summary' => 'A GPU support accessory that helps reduce sag and keeps heavier graphics cards better aligned.', 'description' => 'Support stand for users installing larger graphics cards in gaming and creator desktop builds.', 'highlight' => 'Cleaner GPU alignment for larger and heavier cards.', 'price' => 149000, 'stock' => 28, 'is_featured' => 0, 'sort' => 1206],
                ['sku' => 'CLG-DST-07', 'name' => 'CaseCare Dust Filter Set', 'slug' => 'casecare-dust-filter-set', 'summary' => 'A dust filter kit for cleaner intake management and easier long-term PC maintenance.', 'description' => 'Case filter set for builders who want to reduce dust buildup and keep cleaning schedules simpler.', 'highlight' => 'Cleaner airflow paths with less dust entering the system.', 'price' => 129000, 'stock' => 33, 'is_featured' => 0, 'sort' => 1207],
                ['sku' => 'CLG-HUB-08', 'name' => 'FanSync PWM Hub', 'slug' => 'fansync-pwm-hub', 'summary' => 'A compact fan hub that makes it easier to control multiple cooling fans from one cleaner point.', 'description' => 'PWM fan hub designed for cases that need easier cable and fan control management.', 'highlight' => 'Simpler control for multi-fan builds and tighter cases.', 'price' => 189000, 'stock' => 26, 'is_featured' => 0, 'sort' => 1208],
                ['sku' => 'CLG-LGT-09', 'name' => 'AuraSide Tempered Panel Kit', 'slug' => 'auraside-tempered-panel-kit', 'summary' => 'A tempered side panel kit that helps showcase cleaner internal builds and coordinated lighting.', 'description' => 'Aesthetic case panel upgrade for builders who want a more polished showcase look.', 'highlight' => 'Cleaner build presentation for RGB and cable-managed systems.', 'price' => 319000, 'stock' => 14, 'is_featured' => 0, 'sort' => 1209],
                ['sku' => 'CLG-SLV-10', 'name' => 'CleanRoute Cable Sleeve Pack', 'slug' => 'cleanroute-cable-sleeve-pack', 'summary' => 'A cable sleeve pack for better internal case organization and neater visible wiring.', 'description' => 'Cable management accessories for builders who want a cleaner interior and easier maintenance access.', 'highlight' => 'Tidier internal layout for cleaner-looking desktop builds.', 'price' => 99000, 'stock' => 45, 'is_featured' => 0, 'sort' => 1210],
            ],
            'desk-furniture-ergonomics' => [
                ['sku' => 'ERG-ARM-01', 'name' => 'PostureLift Monitor Arm', 'slug' => 'posturelift-monitor-arm', 'summary' => 'A gas-spring monitor arm for cleaner screen positioning and more comfortable desk posture.', 'description' => 'Desk arm that helps users raise monitors, reclaim desk space, and create better alignment during long work hours.', 'highlight' => 'Better posture and cleaner monitor positioning for daily desk use.', 'price' => 799000, 'stock' => 16, 'is_featured' => 1, 'sort' => 1301],
                ['sku' => 'ERG-MAT-02', 'name' => 'SoftStep Desk Mat XL', 'slug' => 'softstep-desk-mat-xl', 'summary' => 'A large desk mat that helps unify keyboards, mice, and accessories into a cleaner surface.', 'description' => 'Extended desk mat built for comfort, cleaner placement, and a more refined daily workspace look.', 'highlight' => 'A simple desk upgrade that makes the setup feel cleaner instantly.', 'price' => 239000, 'stock' => 41, 'is_featured' => 0, 'sort' => 1302],
                ['sku' => 'ERG-RST-03', 'name' => 'ComfortWave Wrist Rest Set', 'slug' => 'comfortwave-wrist-rest-set', 'summary' => 'A wrist support set for keyboard and mouse users who want a softer, more stable desk feel.', 'description' => 'Desk comfort accessory set aimed at reducing strain during longer typing and pointer sessions.', 'highlight' => 'Extra desk comfort for daily typing and mouse use.', 'price' => 169000, 'stock' => 35, 'is_featured' => 0, 'sort' => 1303],
                ['sku' => 'ERG-RSR-04', 'name' => 'LevelUp Monitor Riser', 'slug' => 'levelup-monitor-riser', 'summary' => 'A compact riser that lifts screens and creates extra space for keyboards or notebooks below.', 'description' => 'Monitor riser designed for cleaner posture and better small-desk organization.', 'highlight' => 'Extra desk space and cleaner screen height in one move.', 'price' => 289000, 'stock' => 24, 'is_featured' => 0, 'sort' => 1304],
                ['sku' => 'ERG-LMP-05', 'name' => 'FocusBeam Study Lamp', 'slug' => 'focusbeam-study-lamp', 'summary' => 'A practical lamp for desks that need better lighting during long work or study sessions.', 'description' => 'Desk lamp built for focused reading, task work, and more comfortable daily desk lighting.', 'highlight' => 'Brighter desk visibility without harsh room glare.', 'price' => 359000, 'stock' => 20, 'is_featured' => 0, 'sort' => 1305],
                ['sku' => 'ERG-FST-06', 'name' => 'FootEase Under Desk Rest', 'slug' => 'footease-under-desk-rest', 'summary' => 'An under-desk footrest that helps improve comfort during long periods of seated work.', 'description' => 'Desk comfort accessory for home and office workers who spend long hours sitting.', 'highlight' => 'Small ergonomic support that makes long desk hours easier.', 'price' => 269000, 'stock' => 18, 'is_featured' => 0, 'sort' => 1306],
                ['sku' => 'ERG-CHR-07', 'name' => 'SupportOne Ergonomic Chair', 'slug' => 'supportone-ergonomic-chair', 'summary' => 'A supportive chair designed for longer workdays, cleaner posture, and more consistent seated comfort.', 'description' => 'Ergonomic office chair for users building better daily comfort into work and study spaces.', 'highlight' => 'Long-session comfort with posture support built in.', 'price' => 2999000, 'stock' => 6, 'is_featured' => 1, 'sort' => 1307],
                ['sku' => 'ERG-DSK-08', 'name' => 'RiseDesk Compact Standing Desk', 'slug' => 'risedesk-compact-standing-desk', 'summary' => 'A compact adjustable desk for switching between seated and standing work throughout the day.', 'description' => 'Standing desk solution for users who want more flexibility and movement in tighter home offices.', 'highlight' => 'Flexible work posture in a desk-friendly compact footprint.', 'price' => 3899000, 'stock' => 5, 'is_featured' => 1, 'sort' => 1308],
                ['sku' => 'ERG-BRD-09', 'name' => 'DeskDock Accessory Shelf', 'slug' => 'deskdock-accessory-shelf', 'summary' => 'A shelf add-on for organizing chargers, notebooks, and small desk tools more neatly.', 'description' => 'Desk shelf for creating clearer vertical storage on crowded workspaces.', 'highlight' => 'More desk organization without taking extra floor space.', 'price' => 219000, 'stock' => 22, 'is_featured' => 0, 'sort' => 1309],
                ['sku' => 'ERG-CBL-10', 'name' => 'TidyLine Under Desk Tray', 'slug' => 'tidyline-under-desk-tray', 'summary' => 'An under-desk tray that hides adapters and excess cables for a cleaner visible setup.', 'description' => 'Cable tray designed to reduce visible clutter and make desk setups easier to maintain.', 'highlight' => 'Cleaner underside routing for tidier desk presentations.', 'price' => 199000, 'stock' => 27, 'is_featured' => 0, 'sort' => 1310],
            ],
            'console-handheld-gear' => [
                ['sku' => 'CSL-CASE-01', 'name' => 'PlayGuard Console Carry Case', 'slug' => 'playguard-console-carry-case', 'summary' => 'A travel case for protecting handheld consoles, accessories, and small gaming essentials on the go.', 'description' => 'Protective carrying case built for portable gaming setups and cleaner travel organization.', 'highlight' => 'Portable protection for handheld gaming and travel accessories.', 'price' => 279000, 'stock' => 29, 'is_featured' => 1, 'sort' => 1401],
                ['sku' => 'CSL-DCK-02', 'name' => 'GamePort Handheld Dock', 'slug' => 'gameport-handheld-dock', 'summary' => 'A dock that helps turn handheld gaming into an easier big-screen or desk-connected experience.', 'description' => 'Docking accessory built for handheld users who want easier charging, display output, and tidy desk placement.', 'highlight' => 'Easy docking for handheld play, charging, and display use.', 'price' => 599000, 'stock' => 15, 'is_featured' => 1, 'sort' => 1402],
                ['sku' => 'CSL-PAD-03', 'name' => 'GripFrame Console Cover', 'slug' => 'gripframe-console-cover', 'summary' => 'A protective grip cover that improves comfort and helps reduce slips during portable gaming sessions.', 'description' => 'Console grip shell for handheld users who want a more secure hold and extra edge protection.', 'highlight' => 'More comfortable handheld grip with added protection.', 'price' => 189000, 'stock' => 31, 'is_featured' => 0, 'sort' => 1403],
                ['sku' => 'CSL-CHG-04', 'name' => 'PowerPlay Charging Dock', 'slug' => 'powerplay-charging-dock', 'summary' => 'A charging dock that gives controllers and handheld accessories a more organized home between sessions.', 'description' => 'Gaming dock for users who want quicker charging access and a tidier entertainment setup.', 'highlight' => 'Cleaner charging and neater storage for gaming accessories.', 'price' => 339000, 'stock' => 18, 'is_featured' => 0, 'sort' => 1404],
                ['sku' => 'CSL-CBL-05', 'name' => 'QuickSync HDMI Cable Set', 'slug' => 'quicksync-hdmi-cable-set', 'summary' => 'A cable set for connecting consoles, docks, and display devices with less guesswork.', 'description' => 'HDMI cable pack aimed at entertainment desks, portable docks, and multi-screen gaming setups.', 'highlight' => 'Practical cable bundle for console and dock connections.', 'price' => 129000, 'stock' => 43, 'is_featured' => 0, 'sort' => 1405],
                ['sku' => 'CSL-CTL-06', 'name' => 'DualCore Wireless Controller', 'slug' => 'dualcore-wireless-controller', 'summary' => 'A controller built for comfortable casual play, co-op sessions, and everyday entertainment setups.', 'description' => 'Wireless game controller designed for console and PC users who want a balanced all-purpose option.', 'highlight' => 'Comfortable control for casual gaming and shared play.', 'price' => 699000, 'stock' => 12, 'is_featured' => 0, 'sort' => 1406],
                ['sku' => 'CSL-AUD-07', 'name' => 'PartyChat Console Headset', 'slug' => 'partychat-console-headset', 'summary' => 'A lightweight headset made for voice chat, co-op play, and cleaner everyday console audio.', 'description' => 'Gaming headset built for console players who need clear chat and low-fuss everyday comfort.', 'highlight' => 'Easy voice chat and comfortable listening for longer play sessions.', 'price' => 459000, 'stock' => 20, 'is_featured' => 0, 'sort' => 1407],
                ['sku' => 'CSL-STN-08', 'name' => 'DisplayArc Controller Stand', 'slug' => 'displayarc-controller-stand', 'summary' => 'A simple stand for displaying and storing controllers more neatly on shelves or entertainment desks.', 'description' => 'Controller stand for reducing clutter and keeping favorite gamepads ready to grab.', 'highlight' => 'Neater controller storage for shared gaming spaces.', 'price' => 109000, 'stock' => 26, 'is_featured' => 0, 'sort' => 1408],
                ['sku' => 'CSL-BAT-09', 'name' => 'PlayCell Recharge Kit', 'slug' => 'playcell-recharge-kit', 'summary' => 'A rechargeable battery kit designed for controllers, remotes, and everyday play accessories.', 'description' => 'Battery solution for gamers who want fewer disposable replacements and easier controller readiness.', 'highlight' => 'Rechargeable power that keeps controllers ready more often.', 'price' => 249000, 'stock' => 24, 'is_featured' => 0, 'sort' => 1409],
                ['sku' => 'CSL-BAG-10', 'name' => 'TravelMode Console Sling Bag', 'slug' => 'travelmode-console-sling-bag', 'summary' => 'A compact sling bag for handheld gaming gear, chargers, cables, and light travel essentials.', 'description' => 'Portable gaming bag designed for handheld users who want cleaner organization on the move.', 'highlight' => 'A smarter carry option for portable gaming essentials.', 'price' => 359000, 'stock' => 17, 'is_featured' => 0, 'sort' => 1410],
            ],
        ];

        foreach ($productsByCategory as $categorySlug => $products) {
            $categoryId = $categoryMap[$categorySlug]['id'] ?? null;
            if ($categoryId === null) {
                continue;
            }

            foreach ($products as $product) {
                $payload = [
                    'category_id' => $categoryId,
                    'sku' => $product['sku'],
                    'name' => $product['name'],
                    'slug' => $product['slug'],
                    'summary' => $product['summary'],
                    'description' => $product['description'],
                    'highlight' => $product['highlight'],
                    'price' => $product['price'],
                    'stock' => $product['stock'],
                    'stock_badge' => $this->resolveStockBadge($product['stock']),
                    'is_featured' => $product['is_featured'],
                    'display' => 1,
                    'sort' => $product['sort'],
                ];

                $existingProduct = $productModel->getProductBySlug($payload['slug']);
                if ($existingProduct) {
                    $productModel->updateProductById($existingProduct['id'], $payload);
                    continue;
                }

                $productModel->insertProduct($payload);
            }
        }
    }

    private function resolveStockBadge(int $stock): string
    {
        if ($stock <= 0) {
            return 'Pre Order';
        }

        if ($stock <= 10) {
            return 'Limited';
        }

        return 'Ready Stock';
    }
}
